#+OPTIONS: toc:nil 

* 英文写作
  
最近读了两本书：《[[https://www.amazon.com/Elements-Style-Fourth-William-Strunk/dp/020530902X][The Elements of Style]]》阐述了英文的写作风格，《[[https://www.amazon.com/Practice-Programming-Addison-Wesley-Professional-Computing/dp/020161586X][The Practice of Programming]]》则分享了编程实践。写作和编程，两个看似无关实则有着相当重叠的事情，都强调了风格重要性。

这一年来，自己连续写了十几篇技术文章，也看了不少原版书；对于书中提到的写作／编程风格，都有一种似曾相识的感觉。

于是想通过这篇文章分享一下自己的英文写作体会，尤其是技术类写作。自己的写作也谈不上好，不管是中文还是英文，从高中到大学一直都很头疼。不足之处，请大家见谅并指出错误。

** 为什么用英语写作？

*** 语言习惯的不同

语言是人类用来进行沟通交流的表达方式，每个民族都有自己的语言，它是这个民族的重要特征。中国人表达喜欢委婉含蓄，这个从很多文学作品可以看出来；与之相反，英文的表达方式就比较开门见山了。

还记得我们中学语文考试的阅读理解吗？虽然看懂了文字，但是作者真正想要表达的东西（或者出题人的参考答案）总是很难答出（至少我是这样的，摊手）。举个我很喜欢的例子，鲁迅的《枣树》：

#+BEGIN_QUOTE
在我的后园，可以看见墙外有两株树，一株是枣树，还有一株也是枣树。
#+END_QUOTE

这句话妙在哪里？

一个标准参考答案可以是这样的：表达了鲁迅的苦闷心情。具体的答案可能会很冗长，通过什么手法，使文章更有什么，更突出表达了什么的，诸如此类的。

看了答案之后，的确挺妙的，一个“我很郁闷”写成这样有意思和味道也是厉害了。阅读这样的文字（而不是做阅读理解题）的过程想想可能也是非常有趣的。

英语国家的人大概就不这样写了，可能就是 "I'm down" 这样直接，或者加上一些行为／心理描写，但是你是能从字里行间直接看出的（这也是我觉得中学的英文阅读理解比语文的简单多了，基本上看懂了单词就差不多了）。

*语言没有好坏，只有表达方式上的差异。* 同样的事情，可能有大不相同语言的描述；这种差异同样对应于文字的理解和欣赏。我个人感觉，阅读欧美作品，并不觉得文字有多优美，更多的时候像是在看故事；中文的作品，经常能看到很多文艺相关的东西，比如诗词歌赋，对仗比兴，暗喻讽刺什么什么的，通常我们要更近一步的思考才能理解作者的意图。

*** 简单清晰的表达

从文学欣赏的角度，中文更好；但是从单纯的理解上来看，更直接的语言更合适。然而，在我的印象中，似乎都不喜欢中文直接的表达，这样会显得没有文笔。确实，写到这里我也觉得自己写得太没文笔了。感觉自己上了高中之后，就不会写中文了，大学的时候应该修一门“大学语文”之类的课程。

对于不是从事文学创作的我们来说，简单清晰表达自己可能更合适。当然，这 *并不意味着非要用某种语言，用你适合你自己方式，清晰表达就好了。* 以自己写技术文章为例，用中文时，经常觉得这个描述过于简单，都不符合中文习惯（一方面也是自己中文写作比较差)，然而这就是我想说的，切换到英文就自然多了：我不用考虑文笔不文笔问题，就简单的表达出来，加个逗号，前后挪动从句，加个介词或者连词串起来，倒也不觉得突兀，感觉都是顺着自己阅读别人的写作风格来。

说到写作风格，这里一定要对我最喜欢的两位技术作家表示感谢：[[https://www.kohala.com/start/][Richard Stevens]] 和 [[https://www.cs.princeton.edu/~bwk/][Brian W. Kernighan]]。谢谢你们，不仅仅是知识，还有你们简明清晰的写作风格。

*** 译版，原版？

还是蛮庆幸的，对于专业内容，自己一开始有选择的阅读原版。尽管一开始比较艰难，但是硬着头皮看了几本后就比较轻松了。不管看什么语言的书都有类似的感觉，在你对于某个东西了解得越多，后续阅读类似的只会更快。

不过，对于同一本书，对于原版和译版，尤其是技术图书很多时候差异还是很大的。不少非常经典书都让翻译给毁了，我非常喜欢的一本，[[https://www.amazon.cn/TCP-IP%25E8%25AF%25A6%25E8%25A7%25A3%25E5%258D%25B71-%25E5%258D%258F%25E8%25AE%25AE-W-Richard-Stevens/dp/B00116OTVS][TCP/IP Illustrated]]，就是让翻译给毁了。译版读起来非常不流畅不说，更是错误连篇。这里也说明了，用中文来清晰表达，并且让人阅读，理解起来比较自然技术文字，还是需要一番中文功底的。

所以，有条件可以考虑阅读原版书，只有这样你才能和作者一对一交流。

*** 贴近主流和标准

《The Practice of Programming》里面有两条建议：

- Stick to the standard
- Program in the mainstream

什么是主流，什么又是标准？

不同的行业有不同的回答，在计算机行业，几乎最新最全的资料都是来自英文。若想在这个领域走得越远越快，英文是必须的。

*** 多样化

标准意味着我们的作品与世界各地的朋友交流分享。尽管这可能并没有给你带来多少流量，但是这不应该是最终目的。想象一下，很多时候，理解一个东西最好的办法就是写一篇文章；但是当真正下笔的时候，这事儿并不简单；当你的文章被搜素引擎收录了，某天某个地球上的朋友正在寻找某个问题的内容，恰好你写的东西帮助了它，又或者那位朋友指出了你的错误，引出了更好的办法，这是非常理想的结果。

典型的例子是stackoverflow，github，wikipedia这样的社区，它们已经是实际的标准了。正是那些在来自世界各地，有着不同的文化背景的人们的分享与共享，造就了现在的样子。在那里交流，你会收获到很多。很难想想局限在一个相似背景文化的圈子里会变成这个样子。

*** 写出更好的程序

Brian Kernighan 在 《The Practice of Programming》 中写道：

#+BEGIN_QUOTE
Writing good code has much in common with writing good English.

*Simplicity* and *clarity* are the first and most important, since almost everything else follows from them.
#+END_QUOTE

我想搞程序的朋友应该深有体会了，代码本身就是一堆英文，更不用说相关的各种文档。写程序，某种意义上也是写出你对某个问题的理解，用简单和清晰的代码表达，这是首要的事情，没人会喜欢复杂晦涩。用最简单的办法让把事情搞定，这与英文的表达方式相辅相成。

最后，再次重申一下，语言本身没有好坏，只有更合适某种场合。

** 写作风格

*** 为什么写作风格很重要？

我也在学习，不敢妄言。这里引用还是 [[https://en.wikipedia.org/wiki/E._B._White][E. B. White]] 在 《The Elements of Style》说的：

#+BEGIN_QUOTE
It is old observation that the best writers sometimes disregard the rules of rhetoric. When they do so, however, the reader will usually find in the sentence some compensating merit, attained at the cost of the violation. Unless he is certain of doing as well, he will probably do the best to follow the rules.
#+END_QUOTE

每种语言都有自己的风格，坚持好的风格，无论是写作，还是程序都是值得的。不仅是自己，读者亦会受益。

*** 推荐阅读

1. [[https://www.ietf.org/rfc/rfc2119.txt][RFC 2119]]
2. The Elements of Style
3. The Practice of Programming

** EOF

#+BEGIN_SRC yaml
title: 英文写作
date: 2017-03-19T17:46:31+08:00
summary: 关于英文写作的体会
weather: rainy
license: cc-40-by
location: 22,144
background: teos.jpg
tags:
  - Writing
#+END_SRC


感谢阅读。
