* 给果果的一些工作信息(持续更新中...)

** 要求

坐办公室的，不到处乱跑的，不受坑爹领导气的，不搬运东西的，没有太多的饭局，符合你老年人作息的，福利待遇要好的，最好还是我家医学编辑:)

** 药品注册

*** new - 注册专员 - 深圳市罗素医药有限公司 - 8-15k

http://jobs.51job.com/shenzhen-ftq/74655109.html?s=01&t=0

pros

- 薪资看起来挺好
- 招若干人
- 1年经验优先

cons

- 若有兴趣，可以深入了解

*** 药品注册专员 - 深圳市康哲药业有限公司 8-10k

http://jobs.zhaopin.com/120570119252385.htm?ssidkey=y&ss=201&ff=03&sg=4fcbe47bdda04729ad1634cd9329a8bf&so=1

pros

- 公司挺大的，是名企
- 地点很好
- 福利看起来也很好
- 求职反馈率很高，看起来很有招人的意愿
- 有一年以上新药研发或药品注册工作经验者优先，优先，优先，我可以理解为不是硬性条件嘛？
- 任职资格看起来你挺符合的

cons

还没发现
*** new - 注册专员管培生 - 深圳市康哲药业有限公司 7-8.5k

pros

- 这公司和前面那个一样
- 不需要经验，感觉你挺符合的
- 管培生，意味着会培养新人吧

cons

- 管培生，不知道怎么样，感觉不如上面那个专门的注册专员？

*** 药品注册专员 - 深圳爱生再生医学科技有限公司 10-15k

http://jobs.zhaopin.com/551400528250104.htm?ssidkey=y&ss=201&ff=03&sg=4fcbe47bdda04729ad1634cd9329a8bf&so=5

pros
- 薪资挺好的
- 说是有 有一年以上新药研发或药品注册工作经验者优先。优先，就意味着不是必要条件？

cons

- 地点较偏
- 公司人数写着不超过100人

*** 国际注册专员 - 深圳翰宇药业股份有限公司 8-10k

http://jobs.zhaopin.com/238469316250816.htm?ssidkey=y&ss=201&ff=03&sg=d1339a2270264e9d87c8dfbed0e6dfc9&so=1

pros

- 经验一年以下
- 地点在科技园，挺好的
- 只要求本科以上学历，不知道算不算是个优势，也可能是劣势。。
- 另外也招研发，参看下面

cons

工作要求挺简单，就一句话，感觉没说清楚。

*** old - 注册专员 - 科曼医疗 8-10k

https://www.lagou.com/jobs/3994842.html

pros

- 硕士及以上，经验不限

*** new - 药品注册专员 - 深圳市康哲药业有限公司 8-15k

http://jobs.51job.com/shenzhen-nsq/78363784.html?s=04

看起来需要2年经验，硕士以上，英语要好，包住，另外工作位置也挺好


** CRA

需要经常在外面出差，看起来薪资也不如药品注册和研发。但是你有项目经验。感觉这个职位在外企最好了。

有个关键的问题：职位要求有x年经验的，你愿意去尝试么？

*** new - 临床监察员 - 深圳信立泰药业 - 面议

http://muchong.com/t-11349615-1

看这帖子发的时间可能有点晚了，不过留了联系方式，还是可以试试的。看介绍说是中国医药工业板块股票市值前十名，中国医药上市公司竞争力20强。

帖子里面的要求是：专业相关，经验不限，硕士以上学历，愿意到深圳长期发展。

*** new -【CRA招聘】PAREXEL精鼎中国全国范围内招聘

https://zhuanlan.zhihu.com/p/31056606 https://zhuanlan.zhihu.com/p/31522435

欢迎私信咨询或直接发简历至chaikuan@live.cn

知乎上看到的，下面的回复挺多，应该是个好外企，在深圳也有驻地。

说是至少半年以上临床监查员相关工作经验，看起来连一年都不到呢，可以试试看

*** new - 临床专员 - 安徽九华华源药业有限公司 - 8-12w 年薪

http://jobs.51job.com/shenzhen/86343644.html?s=01&t=0

pros

- 无经验

cons

- 酬薪低

*** new - 临床专员（CRA）- 江苏量点科技有限公司 - 8-10k

http://jobs.51job.com/shenzhen-nsq/96284575.html?s=01&t=0

pros

- 相对所有的CRA招聘里面较好的

cons

- 需要经验

*** new - CRA - 丽珠医药集团股份有限公司 - 6-8k

http://jobs.51job.com/shenzhen-nsq/93505063.html?s=01&t=0

cons

- 看起来工资一般
- 需要经验。。
- 有些只需要大专的学历就有这个工资了


** 研发

*** new - 创新中心研发人员 - 深圳市健开医药有限公司 6-8k

http://jobs.zhaopin.com/163013714250006.htm?ssidkey=y&ss=201&ff=03&sg=41a8ce8074054edbb795dc07fd313973&so=51

pros

- 要求硕士，药学专业， 重点是 *不需要经验*
- 公司办公地点非常好
- 比较推荐

*** new - 制剂研究员 - 深圳万乐药业有限公司 8-10k

http://jobs.zhaopin.com/132030117250740.htm?ssidkey=y&ss=201&ff=03&sg=41a8ce8074054edbb795dc07fd313973&so=45

pros

- 研究生学历，药学或药剂学等相关专业
- 一年以上制剂工艺研究工作经验，不知道你有没有- -
- 地点还是挺好的，不偏

*** 深圳翰宇药业股份有限公司 - 制剂研究员 8-10k

http://jobs.51job.com/shenzhen/94589095.html?s=04

pros

- 不需要经验，硕士以上，招5人
- 工作地点在南山区科技园
- 免费早餐午餐、住宿，节庆费用、五险一金、活动经费、带薪年假、班车上下班接送等等
- 也招药品注册，也没有说经验，也可以试试

cons

- 还不知道加班怎么样，毕竟在科技园
- 是不是真的不要求经验？给员工的培养规划怎么样也不知道


*** 正中医药集团有限公司 - 药品研发立项 8-15k

http://jobs.51job.com/shenzhen-nsq/87503182.html?s=04

pros

- 没要求经验，考虑优秀的毕业生，说明确实不要求经验呢
- 薪水看起来还不错
- 科兴科学园园区很好
- 也招药品注册，但写了2年经验 http://jobs.51job.com/shenzhen-nsq/87256973.html?s=04

cons

尚未调查


*** 技术/研发人员 - 深圳市中核海得威生物科技有限公司 15-20k

http://jobs.zhaopin.com/000625805250266.htm?ssidkey=y&ss=201&ff=03&sg=4fcbe47bdda04729ad1634cd9329a8bf&so=2

看起来啥都挺好，就是要经验，但是我觉得可以试试投一下，反正也没啥损失，要是他们看中了你的潜力愿意培养你呢？ps，他们反馈率很高。


*** new - 医药研发人员 - 深圳市健开医药有限公司 - 8-10k

http://jobs.zhaopin.com/163013714250005.htm?ssidkey=y&ss=201&ff=03&sg=515390a08db54f88975b776e555d385b&so=1

pros

- 地点不错
- 经验不限，真的么？

*** new - 药物化学科研人员 - 北京睿熙生物科技有限公司 - 6-8k

http://jobs.51job.com/shenzhen-nsq/99091335.html?s=01&t=0

pros

- 貌似硕士生就直接要了

cons

- 这公司人不多，薪资看起来也不高，说是依据经验给予不同的职位和待遇；可以试试？
** 医学编辑

编辑的薪资看起来是以上几个里面较低的，但是感觉工作内容较简单吧，有的招聘学历起点也低呢，肯定是坐办公室的，白领吧= =

招聘的公司相对来说有点杂乱的样子，有的需要互联网自媒体的一些相关经验。

*** 腾讯 - 医学策划编辑

http://hr.tencent.com/position_detail.php?id=34114&keywords=%E5%8C%BB%E5%AD%A6&tid=0&lid=0

原话：MIG下的一个前景挺好的部门，市面上还没有竞品，类似于医疗百科之类的，需要医学相关背景专业且对医学类写作有比较深入经验的

试一试吧，试了也没啥损失嘛

*** new - 医学编辑 - 香港诺嘉国际 - 8-10k

https://www.zhipin.com/job_detail/1417115950.html?ka=search_list_4

pros

感觉要求你都特符合，除了经验

cons

公司不是药企


*** new - 医学编辑 - 健康160 - 7-14k

http://jobs.51job.com/shenzhen-nsq/89168709.html?s=01&t=0

pros

- 互联网医疗公司，貌似用过这产品

cons

- 需要经验，能力强可放宽。。

*** new - 医学编辑 - 玄关健康 - 6-12k

https://www.lagou.com/jobs/4158185.html

互联网公司，不限


*** new - 其他医学编辑招聘

https://www.zhipin.com/job_detail/?query=医学编辑&scity=101280600

http://search.51job.com/list/040000,000000,0000,00,9,99,%25E5%258C%25BB%25E5%25AD%25A6%25E7%25BC%2596%25E8%25BE%2591,2,1.html?lang=c&stype=&postchannel=0000&workyear=99&cotype=99&degreefrom=99&jobterm=99&companysize=99&providesalary=99&lonlat=0%2C0&radius=-1&ord_field=0&confirmdate=9&fromType=&dibiaoid=0&address=&line=&specialarea=00&from=&welfare=

https://www.lagou.com/jobs/list_医学编辑?labelWords=&fromSearch=true&suginput=

** 公务员

不是太了解，但如果是专业对口的，那看起来也非常不错呢。

** 其他

- 广州
- 2013年国内药企新药注册申报前100名 深圳致君制药有限公司
- 深圳万乐药业有限公司 http://www.wanle.com.cn/07contact/index04.asp 貌似招的都是有经验的。。

** 一些问题

- 具体的专业
- 英语怎么样，写文案怎么样
- 有不有相关的经验，实习的？
- 最想做那个工作？
- GCP
- 药企办公司做学术？
- 离职了之前扣的工资还有垫资会拿回来吧
- 新开的研究室会招这样的新人
- 大药企，做学术？但工资低。。。
- cra对学历要求不高
- 四个方向：医药公司、医院、公务员、医疗相关的互联网 https://www.zhihu.com/question/38519875
- 研发需要读博么


** 参考资料

- http://muchong.com/html/201710/3455630.html
- https://www.zhihu.com/topic/19802815/hot
- http://muchong.com/bbs/ 信息量很大
- [[http://www.dxy.cn/bbs/topic/37715211][药学出身，如何选择最适合自己的职业？]]


*** 药品注册资料

- 一位药品注册专员的思考 http://blog.sina.com.cn/s/blog_476ae5260100z7kx.html
- 不知道各个企业的药品注册专员都在忙些什么 （学术论坛，信息量很大） - http://muchong.com/html/201105/3226418_2.html
- 想做药品注册专员，望各位大虾给点建议 -  http://muchong.com/html/201708/1693141.html

*** CRA

- [[https://www.zhihu.com/question/22129906][CRA主要工作内容是什么？如何规划？如何做好？需要强化什么技能？需要具备适应什么条件？]]
- [[https://www.zhihu.com/question/23080421][CRA 优缺点]]

** EOF

#+BEGIN_SRC yml
summary: find a good job for fruit!
weather: fine
license: cc-40-by
hide: true
location: 22, 144
background: wawa.jpg
tags: [misc, fruit]
date: 2018-01-20T17:49:52+08:00
#+END_SRC
