* 李果

- +8618390832810‬
- 天津 - 河东区
- liguo310@163.com
- 党员
- https://fruitli.com

#+BEGIN_QUOTE
1. 如果想要投递的岗位公司与目前地点不一样，可以考虑改改
2. 党员酌情写，看应聘的公司岗位
3. 可以把简历挂到个人网站上，我在想，以后有些时候你可以写一些专业相关的文章？然后放到这网站上面，能体现你的文字水平并且表现对行业（医药，互联网）的热爱
#+END_QUOTE

** 教育信息

*** 中南大学（985）- 药学 - 硕士（2014-2017）

专业排名15/54, 一等国家学业奖学金

*** 天津医科大学（211）- 药学 - 本科（2010-2014）

专业排名 4/57, 一等校级奖学金 (1/54)

*** 英文水平 - CET6（514）

#+BEGIN_QUOTE
1. 放到技能证书那块也许更好？
2. 写一下对英语的应用水平，比如能够熟练地阅读专业相关的文献，听说读写等。
#+END_QUOTE

** 工作&实践经历

#+BEGIN_QUOTE
1. 时间倒叙，以下同
2. 2-3句话描述你做了那些工作（不是你的职位描述，而是你做了哪些内容）；比如不要写「负责完成销售指标任务」，而是写「通过xxx做销售，达到了xxx效果」。用公式来说就是 *Accomplished X by implementing Y which led to Z.*
3. 职位挪到下一行，不与公司同行？具体看版本吧。另外感觉月份用.号分隔不太好看？
#+END_QUOTE

*** 东阿阿胶股份有限公司 - 天津 - 管理培训生（营销）（2017.07-至今）

2017年度销售任务完成率108.3%，同比2016年增长150.1%

#+BEGIN_QUOTE
这个是达到的效果，实际做了那些内容并没有写。
#+END_QUOTE

*** 湖南长沙晶易医药科技有限公司 - 长沙 - 项目助理 （2014.09-2017.7）

熟练操作HPLC、LC-MS/MS、酶标仪、Malvern粒径仪、细胞培养、MTT、微透析技术等

#+BEGIN_QUOTE
1. 时间要注意下，我看2个简历的时间有些都不一样呢
2. 这个适合写到「技术能力」那一块，还是前面题头说的2-3句话。
#+END_QUOTE

*** 天津市第一中心医院 - 天津 - 实习生 （2013.07-2013.08）

门诊药房、住院部药房、临床药学等科室轮转。

#+BEGIN_QUOTE
1. 感觉如果公司包含地点不用写也OK？
2. 看起来写了做了什么，因为是实习，看看能不能写一些收获心得，学到了什么这类的？
#+END_QUOTE

*** 天津医科大学药学院学生会 - 宣传部部长 （2011.09-2013.11）

组织举办“乐在津医“四格漫画大赛与“五四”主题晚会。

#+BEGIN_QUOTE
组织举办应该是一个过程，里面应该会出现一些问题，是通过什么解决的（简历里没写，面试的时候也许会问到呢？）？大赛与晚会的效果怎么样？

btw, 这个是不是可以考虑放到下面的「奖项与领导力」那块？
#+END_QUOTE

*** 其他，志愿者，参会者，会务成员

#+BEGIN_QUOTE
这几个感觉好像没有说明什么问题，你再想想，能不能挖掘出一些不同的东西来写？
#+END_QUOTE

** 项目经验

#+BEGIN_QUOTE
2-3句话描述你在项目中 *做了哪些工作* 。

第1句话可以说，项目的目标是什么，我在里面负责哪一部分；
第2句话可以说这个工作有一两个比较难解决的地方，自己通过某种方式解决了。
第3句话可以说明结果，成绩，比如质量提升，掌握了什么技能？

如果项目挺好，并且能够给别人看到的，提供一个链接吧！保不准看简历的人点了然后感兴趣呢？

不需要把所有的项目都罗列出来，选择最能体现能力和解决问题的就可以了
#+END_QUOTE

*** 非那雄胺经皮给药制剂的构建及其皮肤渗透性研究 （2015.09-2016.12）

项目负责人。

构建新型非那雄胺载药系统，解决其皮肤渗透性及药物水溶性差。掌握LC-MS/MS、HPLC、微透析技术。已申请相关专利，掌握专利攥写规程。

#+BEGIN_QUOTE
看起来这应该是你重点要写在简历上的了。感觉描述的简单了。（新型系统，新在哪里？把项目的目标再说清楚些）
通过什么方式 解决其皮肤渗透性及药物水溶性差 的？
掌握那几个技术算是结果，可以考虑放到「技术能力」那块，申请专利也是成绩，有专利链接么，放上去最好了。
掌握专利攥写规程，这个是不是对应聘医院注册有帮助？？
#+END_QUOTE

*** 999 牌强力枇杷露中吗啡和可待因的人体药动力学研究 （2015.08-2016.04）

健康受试者招募，样品采集与检测。

#+BEGIN_QUOTE
emmm，写得过于简单了，可能不是太好写，但是是不是可以从招募里面入手？
怎么招募的，遇到啥问题，咋解决的？
样品采集与检测，这里你看看对照题头说的，还能写啥不？
#+END_QUOTE

*** 中国医药科技出版社 -- 《生物药剂学与药物动力学》（2015.08-2016.06）

编辑负责人，负责《口服药物的吸收》章节，编写专业性与趣味性结合的教材；文字排版，图表排版

#+BEGIN_QUOTE
「专业性与趣味性」是这教材的目标吧，然后你负责某个章节，那么是如何实现这个目标的呢？有遇到个啥问题不？

这书有链接么，链一个也好呀。

文字，图表排版是不是可以用在应聘编辑的职位上？
#+END_QUOTE

*** 氟非尼酮亚精胺修饰纳米粒抗百草枯中毒致肺纤维化 （2015.08-2016.01）

亚精胺修饰纳米粒细胞靶向摄取研究；掌握细胞复苏冻存，传代，MTT研究技术

#+BEGIN_QUOTE
1. 感觉项目目标没说清
2. 遇到啥问题，参考前面
3. 掌握了技术也可以作为成果吧，但是项目的结果呢？论文，还是什么的？有就列上去吧。
#+END_QUOTE

** 学术成果

#+BEGIN_QUOTE
首先我觉得一个学术成果应该是有研究的吧，可以视为一个项目，那么作为项目放到「项目经历」是否更合适呢？
btw，学术成果就是项目天生的成果，成绩？
#+END_QUOTE

*** 《雄性激素性脱发的机制及其西药局部治疗研究进展》 

一作

#+BEGIN_QUOTE
1. 时间呢
2. 链接呢
3. 作为项目经历的成果好一点吧？
#+END_QUOTE

*** Role of Cytochrome P450 in human metabolism of SM-1, a potential anti-tumor drug 会议论文集摘要

一作

#+BEGIN_QUOTE
同上
#+END_QUOTE

*** Preparation of ﬁnasteride ultradeformable liposomes-based gel to enhance drug skin rerention in epidermis and dermis  SCI在投

一作

#+BEGIN_QUOTE
同上
#+END_QUOTE

** 技术能力

#+BEGIN_QUOTE
列出自己会使用的专业技术，以及熟练程度（了解，熟练？）。

这个可以对应某个职位的要求写，比如某职位要求 「熟悉xxxx技术」，那就正好了。

我看你上面列了好些技术名次，可以考虑写在这儿？
#+END_QUOTE

- Photoshop, Chemdraw, Origin；MS Office
- 擅长PPT制作与演讲
- others...

#+BEGIN_QUOTE
- 那几个软件，列一下熟练程度，
#+END_QUOTE

** 奖项和领导力

#+BEGIN_QUOTE
- 列出所有的奖项
- 列出所有的体现领导才能的经历
- 不同寻常的经历？想一想，有最好，没有也没关系。（比如我开头给你的建议，经营个人网站，在上面写东西，不过现在还没有做=-=）
#+END_QUOTE

- 计算机二级
- 初级药师（西药）证书
- 实验动物专业培训证书

#+BEGIN_QUOTE
- 宣传部部长的经历你看看放这里合不合适？
- 也可以考虑与「技术能力」合并在一块，就像你之前的，「证书与技能」
#+END_QUOTE

** 其他注意的地方

- 照片，某些岗位是不是可以考虑放生活照：）（开玩笑，溜了。。）
- 这份简历我可以帮你放到 https://fruitli.com 上
- 注意错别字，有些字我是照抄手打的，可能会错，尤其是专有名字。多监察一下
- 能重点突出你的个人部分的部分请加粗或者下划线来高亮
- 只讲事实，简历上的东西都有可能会被问到的
- 自我评价可以写，但是不要太关注这个
- 简历一页纸就好了，这里只是综合2份简历把所有的内容都列了出来，最终还是要取舍
- 我觉得可以适当的在简历中表现一下 *学习能力* ，再说了，你学习本来就很好呀！
- 最后，排版简单，层次清晰

** EOF

#+BEGIN_SRC yaml
summary: 李果简历
hide: true
weather: fine
license: cc-40-by
location: 22,114
background: fruit-happy-birthday.jpg
tags: [Fruit, misc]
date: 2018-03-11T19:16:29+08:00
#+END_SRC
