* 那些和足球有关的事

18年俄罗斯世界杯刚刚开打，不知不觉间，作为一个伪球迷，看球已经12年了。

** 初识

第一次有记忆的看球是在02年韩日世界杯，那时还是在上小学，每天晚上放学回家吃饭的时候都看到大人们盯着电视机看着几十个人在草地上追逐着一个球。也许和大多数人不看球一样，感觉这好无聊啊，完全不理解大人们为啥那么激动。难道不应该看电视剧或者动画片么，然而家里只有一个电视。那场比赛中国队0:3输给了巴西队，记得了一个叫罗纳尔多的外星人。

第二次看球是4年后的德国世界杯。凑凑热闹，跟着大人们一起看捷克vs美国，当时觉得美国一定很强，谁知道开场几分钟捷克就进了一个头球，接下来有个小个子球员进了两个漂亮的远射，一个人就干倒了美国队，牛逼啊。他叫罗西基，于是我第一场就成了捷克的粉丝。可惜，小组赛后两场连输意大利和加纳，小组赛出局。最后队长内德维德跪在球场轻吻草皮的告别令人动容，这是他职业生涯的最后一场球。还有一个球员也是要在这届杯赛退役，那就是和他曾在尤文的队友，法国球星齐达内。捷克被淘汰后，跟风支持了有齐祖的法国队，反正我什么也不懂哈哈哈。1/8淘汰赛轻取西班牙，那时候西班牙纸面上很强，淘汰赛就被打回原型了，斗牛士从来没有赢得任何的冠军。1/4面对五星巴西，那时候桑巴军团有如日中天的小罗，还不是那么肥的大罗，还有帅气的卡卡等一干球星，然而踢得昏昏沉沉，被法国亨利如刺客般的进球给送回南美老家，助攻的是齐达内。半决赛对葡萄牙，那时候菲戈还在，C罗还是个愣头青，哦，不对，大家还叫他小小罗，整场比赛节奏都被法国队牢牢掌控，最后进球的不记得是谁了。决赛对阵意大利队，结局很戏剧化，齐达内头顶马特拉齐被罚下场，最后点球大战告负遗憾未能夺冠。齐达内与大力神杯的背影也许是世界杯历史最经典的照片之一吧。真的很难想象，一直踢的优雅的齐祖竟会有这样的行为。赛后，我也久久不能释怀，还写了个日志啥的，告诫自己别太冲动了。12年后，齐祖在执教生涯也立了个前无古人，后无来者的flag，作为球员和教练，把该赢奖杯的都赢了，这才是人生赢家。

虽然看不懂球，还是很认真的看了好几场比赛。这届杯赛涌现出了几个影响接下来10几年的球员，梅西，C罗，卡卡，他们垄断了之后10余年的金球奖，作为球迷，也是一种幸运吧。对我而言，则是开启了12年看球的历程。

** 相遇

人生若只如初见，罗西基，第一次认真看球的那名令我印象深刻的球员，我后面一直在关注他，得知他在世界杯前转会去了阿森纳俱乐部，再于是发现法国的亨利居然也是阿森纳的灵魂人物，这下好了，果断成了阿森纳的球迷。当时庆幸自己选的没错，这只球队崇尚进攻，踢法优雅，05-06赛季打进了欧冠决赛（俱乐部的最高荣誉），只是由于少打一人憾负当时拥有小罗的西甲球队巴塞罗那。并且这只球队有着辉煌的历史，03-04赛季不败夺冠，看过当时的纪念电影，摧枯拉朽，行云流水。在英格兰历史上，夺得顶级联赛锦标次数也是仅次于曼联的，这些东西都是后面才知道的了。说了那么多，其实就为了罗西基，以及亨利。

看球的第一个赛季，是06-07赛季，这个赛季也是阿森纳从老球场海布里搬到北伦敦的新球场，酋长球场，送别了和齐达内齐名的博格坎普后，由亨利担任队长带着一群青黄不接的队员磕磕绊绊的一个赛季。后面来看，作为球迷，宁愿不换球场，可以说自从换了新球场，就没带来好运气，开启了多年无冠之旅。

这个赛季没看几场球，因为要中考，以及还不是很热衷。影响深刻的就是看到了罗西基灵动的几个进球以及对阵曼联，最后时刻读秒阶段，范佩西给亨利传的一个球绝杀了曼联，自己也是挺激动的。赛后，当时还是小弟的范佩西说，相信亨利，没错的。

欧冠赛场，16强就出局了，负于好像是荷甲的埃因霍温吧，当时亨利受伤坚持出场还是没法进球。有个中国球员站在了欧洲顶级赛事的球场上，叫孙祥。

这个赛季就这么着结束了，自己没看几场球，接着上高中了。

** 相知 

06-07赛季结束后，亨利转会巴塞罗那，作为球迷很理解，他的生涯就差一个欧冠冠军，很可惜没有在阿森纳获得。但是他已经为贡献了所有，8年，俱乐部历史射手榜第一，除了欧冠，他得到了所有能得到的，我看过他每一个进球，最牛逼的就是各种对阵热刺，利物浦，皇马的千里走单骑，以及对曼联的世界波吧。这比杜兰特投奔勇士完全不是一个概念。于是，自己也顺理成章成了巴萨球迷，嘿嘿。记得赛季前巴萨来中国踢表演赛，拥有亨利，小罗，埃托奥和梅西的前场四巨头简直无敌呀。我还买了一件巴萨的盗版球衣，印了个14号。

高中军训的时候，班主任说介绍一下自己，我好像是这样说的，「我是英超的阿森纳，西甲的巴塞罗那，还有意甲的AC米兰球迷」。现在想起来，真的是头铁不明觉厉呀哈哈。

至于为啥是AC米兰球迷？因为前一个赛季，卡卡是历史级别的，各种带球奔袭，好像连梅西也拉不住？最后AC米兰拿下了欧冠冠军，顺便说一句，那一年由于电话门事件，意甲联赛一直磕磕绊绊，米兰夺冠不容易。还有一个原因，卡卡很帅？反正不止一次听女生这么说了，哈哈哈。

这个赛季还有一个特别的地方，就是看球不免费了，被一个叫天盛的把版权买了，看一场球得一瓶冰红茶的钱好像。在国内，付费看球这个概念在现在还是在起步阶段，更不用说当时了，球迷根本不买账，而且还有各种渠道可以看球（盗版），没过几年，就再也没有听到天盛这公司了，估计是倒闭了吧。

说回阿森纳。亨利走后，整支球队都很年轻，可以说非常年轻了，80后的罗西基都是大叔了。赛季前媒体问主教练温格目标是啥？夺冠，没人会相信。然后赛季开始之后球队挂起来青春风暴，一波连胜加不败，牢牢占据积分榜头名。成绩好，踢得也美丽，不像某些只会在球门摆大巴的球队。赛季初那段时间自己生病住院了，每次看到阿森纳都能赢，自己也非常都开心。学校旁边有个卖杂志的小店，当时的足球周刊每期5元，在医院都把这杂志翻烂了。

一直过了英超圣诞赛程，球队还是保持在积分榜头名，历史显示很有希望赢得英超冠军。然而，不幸的事情发生了，2月份的一场球，对方球员暴力的铲球使得前锋爱德华多断腿，整支年轻球队都懵了，这场之后一度几轮不胜，最终错失冠军。很遗憾，但是看到了球队的希望，赛季之初没人会认为他们能踢成这样。

这个赛季曼联C罗（小小罗）爆发了，联赛进球如麻，也赢得了欧冠，毫无悬念地拿下了当年的金球奖（个人最高荣誉），从此也开始了他和梅西接下来直到现在10多年对这项荣誉的垄断。

** 相守 

每个赛季之初，球队踢得都很好，顺风顺水，处在争冠行列。尽管球队由于新球场要还贷预算有限，转会市场基本没有球星加盟，不像某些豪门球队，每个夏天都砸出上亿去买人，但球迷仍坚信这支年轻球队有希望拿下冠军。新人不断涌现很让人惊喜，像法布雷加斯，踢的简直不像20出头，大局观很好，还能时不时进球；稍微老一些的如罗西基也是当打之年。进攻？从不担心。中场各个青年才俊不断给范佩西和阿德巴约输送炮弹，而且进攻能力也强，整个英超都羡慕都中前场阵容。

然而这样的球队总觉得缺少了点什么。对，像前队长维埃拉那样坚固的后腰球员。球队进攻踢的好的时候，防守就容易被忽视。但是状态不会一直这么好的，尤其是强强对话，这样的阵容很容易被对手研究透（比如说穆里尼奥，温格对阵他的胜率是个位数吧）。强强对话拼的是防守，以及对手的失误和球星的闪光。进攻打不出来，防守的压力就大。这么看来，阿森纳就像是被抓住了命门。后腰不硬，再加上这么多年来始终不稳固的后防线，很难防得住强队。更要命的是，有些时候前场好不容易进球领先了，后场莫名其妙的失误让对手扳平比分乃至反超，这确实让进攻球员很无奈。然而这样的剧本可以说是家常了。进攻打出来的时候还能打，打不出来防守就是灾难。

赢不了强强对话，是拿不下冠军的。球队每到2，3月就是经常莫名其妙掉链子，一下子跌出争冠行列，落后10几分。赛季末冲刺了，积分榜末端的球队要保级，强队要拿分，阵容打法都被研究过了，所以很难拿分。年轻球员多，也缺少韧性吧。总之，这么多年了，你可能不信，都是重复着这样的剧本：赛季初争冠，赛季末争四，号称争四狂魔。

实在无法理解温格在买人方面为啥总是重攻轻守，后防这么多年都是天团级别。还很固执，后期看温格的赛后媒体发布会，总是各种借口，抱怨（裁判或者对手balabala），看了10多年，自己都有点看不下去了。明眼人都知道，球队问题在哪，可是在赛季末一波连胜拿到前四都欧冠席位后，似乎又乐观了起来，赛季前不去补足弱点。最明显的就是15-16赛季，那个赛季强队各种动荡，阿森纳是明显最被看好的。可是赛季前和冬歇期的转会市场不作为，又重蹈覆辙，让英超冠军落入了名不见经传刚升入英超没多久的莱斯特城拿了冠军。那是最好的时刻，自那以后，球队根本没有机会。

果不其然，即使温格幡然醒悟，16-17和17-18两个赛季球队花了上亿的投入在转会费上，然而已经晚了，对手本来就很强，再加上温格选人上的固执和战术的落后，最后两个赛季连前四都没进。

欧冠赛场上，也是令人很尴尬。虽说球队年年进欧冠，但是几乎年年16强就被淘汰，人送外号欧冠十六郎。话说回来，我真的挺希望球队不进欧冠的，年年进前四，似乎让球队忘了自己的目标是夺冠，真是有点儿搞笑。早些年不进欧冠，也许球队能痛定思痛，早做改变，专心联赛。球队掉链子和进欧冠也有很大的关系，因为欧冠决赛阶段一般在2月后举行，阿森纳16强出局之后，基本上联赛也是萎靡不振，明显是受到了影响。所以我觉得连续16年好像进欧冠并不是啥好事。

从一年无冠，到两年无冠，三年无冠，最后九年无冠。直到14年，大学毕业那年，球队才拿到了一个含金量不是那么高的足总杯。已经很高兴了，当时还和同学在庆祝，终于打破魔咒了。但是呢，在英超和欧冠赛场上球队还是那个老样子。

这么多年没有获得任何冠军，是什么让你坚持着支持球队？

也许是一种执念吧？从06年的罗西基，亨利开始，就莫名的对这球队有好感。上了大学之后，球队的比赛，几乎都场场不落。熬夜看球？经常的。怀念大学的时候，看球囤各种吃的，然后睡到自然醒。刷各种新闻是家常便饭，中学的时候还曾订阅过体坛周报看球队的新闻。

温格坚持自己的建队思路，踢球风格，在他足以伟大的03-04不败赛季夺冠后，足球已经变得功利了。切尔西的穆里尼奥+阿布就是最典型的例子。短时间内资本涌入，烧钱买人，教练踢球保守，防守反击，反正拿到分能拿冠军就行，场面好看关他屁事。在这个变得越来越功利快节奏的时代，老头显得有些落后了，但是仍然为老头的坚持点赞。很难想象，站在他的角度，面对这么多年无冠的批评，甚至是各种要求他下课的呼声，他是怎么面对的，他已经70多岁了。仍然在每个赛季初给球迷带来惊喜，谁知道老头在休赛期做了多少？他已经给球队带来了一座新球场了。

看过知乎的一个答案：

#+BEGIN_QUOTE
人生本来就有很多事是徒劳无功的啊。

爱情不是是非题，而是程度深浅。最初进入爱情状态的时候很是美好，但之后的经营和维持，漫无止境的。
#+END_QUOTE

一次一次里，感到希望，又感到失望，教会我的是坚持，以及在未来的某些时候，事情会变得如你曾经想的那样？

** 离开 

面对多年无冠的压力以及连续两年无缘前四无法进入欧冠，温格还是在17-18赛季末选择了离开。

以前没离开的时候，看到球队踢的那个样子，自己也愤怒，也曾希望他赶紧下课，但是等到他真的离开了，还是不舍。

记得高中的时候，有些时候没法看球，于是加了QQ球迷群，聊到转会市场，有人担心队里的那个球星会被转会到其他俱乐部（比如小法去巴萨）。我说，没关系，只要有温格在就行，他就是灵魂。

那么，现在他离开了，阿森纳还是阿森纳么？我不知道，应该还是吧，20多年的执教，早已烙下了他的风格。新接手的教练不会抛弃球队的文化，他应该丢掉坏的，带来好的，尤其是坚韧和赢球。作为球迷，还是会支持，虽然这两年看球已经很少了。

铁打的俱乐部，流水的球员。看了12年的转会市场，从06年电话门，尤文成了球星超市，到10年皇马今天大手笔相继买入法甲最佳本泽马，意甲最佳卡卡，以及最重要的，英超，毫无疑问也是世界最佳之一的C罗，最后到去年内马尔强行转会大巴黎，造成了球员身价暴涨。

相比那些大手笔转会。阿森纳的转会，大牌少，金额也有限，别的俱乐部转会费记录是7，8千万欧，他的才不到2千万欧（最近几年才有改变）。但是有一点似乎是很特别的，就是从阿森纳主动提出转会出去的球员似乎都没有太好的结果。

从阿德巴约这个大反骨，到队长法布雷加斯，范佩西，还有纳斯里，赫莱布，宋等等，走的时候都是不欢而散而散，最后职业生涯也不是好的归宿。一个很重要的原因的球员为了追求荣誉吧，这么多年无冠，球员确实想去追求荣誉。唉。

最后，还有一部分人，是安静和微笑着离开的，就是罗西基和卡索拉这些。这两位灵动的球员被伤病毁了职业生涯，假设他俩不伤，我觉得至少是在16年是很有机会的，尤其是卡索拉。没他的日子很难受，事实证明厄齐尔不足以委以大任（昨晚的世界杯德国负于墨西哥就说明了问题）。我现在还能想起卡索拉在14年足总杯决赛力挽狂澜的一个直接任意球射门，终于打破了9年无冠的魔咒，解气呀。还有罗西基北伦敦德比对阵热刺的那个进球，球场莫扎特在进球后激动奔跑庆祝的样子，仿佛找回他当年在绿茵场上奔跑的样子。伤病毁了他们，也毁了阿森纳，俱乐部队医也许是最烂的吧，没有之一。

再见，亦是美好，感谢陪伴！

** 尾声 

今天是端午节，正值世界杯激战，祝大伙今日快乐！最后用五月天的一首哥作结吧，送给温格，送给过去的日子。

#+BEGIN_QUOTE
五月天

顽固

作词：阿信
作曲：阿信

我身在 当时你 幻想的 未来里

这个狂热和冲动

早已冷却的如今

你顽固 的神情

消失在 镜子里

只留下 时光消逝的痕迹

每颗心 的相信

每个人 的际遇

每个故事的自己

反复地问着自己

这些年 让步的

你是否 会叹息

有什么 是你永远不放弃

一次一次你 吞下了泪滴

一次一次 拼回破碎自己

一天一天你 是否还相信

活在你心深处 那顽固自己

你追逐 你呼吸

你嚣张 的任性

鼻青脸肿的哭过

若无其事的忘记

如果你 能预知 这条路 的陷阱

我想你 依然错得很过瘾

走过的 叫足迹

走不到 叫憧憬

学会收拾起叛逆

学会隐藏了表情

卸下了 这面具

我想说 谢谢你

谢谢你 一路陪我到这里

一次一次你 吞下了泪滴

一次一次 拼回破碎自己

一天一天你 是否还相信

活在你心深处 那顽固的自己

一次一次你 吞下了泪滴

一次一次 拼回破碎自己

一天一天你 是否还相信

活在你心深处 那顽固的

你当时相信 的那些事情

会在如今 变成美丽风景

每当我迟疑 从不曾忘记

活在我心深处 那顽固的自己
#+END_QUOTE

** EOF

#+BEGIN_SRC yaml
summary: 18年俄罗斯世界杯刚刚开打，不知不觉间，作为一个伪球迷，看球已经12年了。
weather: fine
license: cc-40-by
location: 22, 114
background: ball.jpg
tags: [memory]
date: 2018-06-18T11:35:28+08:00
#+END_SRC
