* 活在当下(26/52)

活在当下。

生活总要留下点什么，于是便有了这篇小记，以一周为单位，看看这周做了什么，随便写写一些见闻和思考。

** 健康

健康排在首位。

先看看睡眠状况，这是个老大难了。由于世界杯看球和有些时间加班或者睡前玩会儿游戏啥的，这周的睡眠时间比较晚，也比较短。数据来自 iPhone 健康。

| Week | fall asleep | get up |
| Mon  |       01:51 |  07:46 |
| Tue  |       00:20 |  07:10 |
| Wed  |       00:53 |  07:01 |
| Thu  |       01:59 |  07:25 |
| Fri  |       01:20 |  07:00 |
| Sat  |       01:34 |  07:09 |
| Sun  |       00:47 |  07:00 |

平均下来，每天睡觉时间差不多6小时，睡得晚的原因前面说了，起得早的原因，一方面是天气热了睡不了太久，另一个重要的原因是得去锻炼一下。以下是这周的运动情况，数据来自 Nike+ Run Club。

| Week | distance/km |  time |
|------+-------------+-------|
| Mon  |        2.04 | 13:48 |
| Tue  |        2.03 | 13:26 |
| Wed  |        2.02 | 12:33 |
| Thu  |        2.03 | 12:40 |
| Fri  |        2.02 | 13:44 |
| Sat  |        2.02 | 12:59 |
| Sun  |        2.04 | 12:49 |

本周全勤～虽然跑的距离不长，速度也跟不上以前了，但就目前这个状况，能出门就是好的了。跑前还会做会儿热身（目前感觉没啥用），跑后也顺便拉伸一下。总体来说还是不得要领，科学健身了解一下吧。另外除了跑步也可以尝试其他的健身项目，只是觉得简单，可以练练耐力。

起早除了要跑步，还有另一个原因就是去买菜，哈哈哈。是不是觉得不太现实？一开始我也觉得是，但是后面习惯了就好了。早上买菜比较新鲜，如果自己下班再去买可能就比较晚没啥可卖的了。唯一的是麻烦的是大妈有点多。从5月开始绝大多数时间都是在家里做饭了，顺便带第二天的午饭到公司吃。解决温饱问题的同时，自己也可以学着体验生活吧。做饭成本主要在于时间，自己就算做成黑暗料理，感觉也比外卖好吃？这也许是心理作用，自己做的饭，跪着也也要吃完。不过确实是饭量也大了，肚子疼的状况几乎没有了。顺便说一句，经常招待室友吃饭。

本周比较遗憾，仅有周五没有下厨房。现阶段主要还是局限在简单的炒菜，当然，味道也是越来越好了。接下来要在色相和菜系上花点时间琢磨一下，听说看视频比较好？另外早上如果有时间可以做做早餐？前几天看了下厨房app搞得一个“早餐马拉松”的活动，看到好多精致的早餐。一日之计在于晨，争取某天也能做到那样吧，哈哈。

** 学尤克里里

这周业余主要花在了学习尤克里里上（当然，还有游戏，逃）。关于起因和经过可能是另一篇博客了。

大抵是5月底买的琴，然鹅的确是本周才开始认真地学和练。话说好像这乐器只要多练就行，几乎不需要乐理知识。每天都有花至少1小时的时间，主要还是周末的练的时间多，当然我觉得把打游戏的时间分配过去应该会很充裕吧，哈哈。。从基础的调音到识谱，每天20分钟的爬格子练习，接着是单音弹奏，琶音，和弦，以及扫弦弹唱。进度还是比较快的，目前是卡在了扫弦弹唱毫无节奏以及几个和弦比较难按得准和稳，还是需要时间来多练吧。现在可以比较有感觉的琶音弹一些小曲了，像《可惜不是你》，《天空之城》。

希望下周能找到弹唱的节奏～

** 阅读

这周看完了3本书，嗯，只是这周看完，有些书之前已经在阅读了。主要的时间是周末早上，跑完步吃完早饭洗漱就去附近的南山图书馆坐一早上，效率很高。

影响最大的是《穷爸爸，富爸爸》。有些道理以前听过，但是真正看完了书才会觉得有血有肉。比如说，

#+BEGIN_QUOTE
穷人和中产阶级为钱而工作，富人让钱为他工作。

他们不明白为什么自己老缺钱，于是以为多挣点钱就能解决问题，几乎没有人意识到缺乏财商教育才是问题的关键。
#+END_QUOTE

听了那么多道理，那么我们应该怎么做呢？emmmm，这里展开了就太多了，后面应该会写一些相关的实践（目前已经在试着来了）。强烈推荐大伙看看这本书。总结一下自己现在想到和能做到的：

- 了解什么是资产负债表
- 关注自己的事业，构筑资产项
- 学点会计和营销的东西
- 首先支付自己，把支出控制在资产带来的收益以下（前提是不以牺牲舒适为代价）

在投资之前，一定得先了解市场，知道自己在做什么。所以现在还是多投资自己吧，这周还看了一会《手把手教你读财报》的书，还没看完，但是看得人一头雾水，所以学点会计是没错的。

另外还看完了阿加莎克里斯蒂的《无人生还》，书不长，类似的手法以前有见过所以看得比较快。这本书开创了童谣杀人和孤岛模式，着实很经典，看完了书还找来电影看了，推荐～

** 事件

有点困了，只说一件事。

大学室友给我从他家乡寄来了一箱芒果。很感动，毕业整整四年了，想起以前的一些事，多谢，睡在我上铺的兄弟。

于是现在可以每天带一个芒果作为下午茶了。

** EOF

#+BEGIN_SRC yaml
summary: 跑步，做饭，尤克里里，阅读，活在当下
weather: fine
license: cc-40-by
location: 22, 114
background: ukulele.jpg
tags: [weekly]
date: 2018-07-03T02:02:24+08:00
#+END_SRC
