* 龙凯

- 13168001399
- 广东 - 深圳 - 南山
- im.longkai@gmail.com
- https://xiaolongtongxue.com

** 教育

广西大学 - 计算机科学与技术 - 本科 (2010 至 2014)

英语六级，能够熟练地阅读原版书籍和撰写英文博客

** 工作经历

*** 深圳瓶子科技（腾讯全资子公司） - iOS/Android/后台 开发工程师（2017-5 至今）

17年负责活点地图的Android和iOS端开发，包括好友地图交互，即时聊天表情动画，好友实时位置的上报和获取等模块。
18年主要负责求知鸟付费课程项目的后台开发，包括API，运营后台服务，推荐系统，ELK日志监控系统，以及将服务迁移到k8s等。

*** 深圳市时时医科技有限公司 - Android 开发工程师 (2015-6 至 2016-3)

负责带领一个3人团队开发病患服务医生端 App。主要工作内容是使用 Socket API 编写自有的即时聊天（IM）模块，实现了医生与医生或患者间的即时沟通，转移患者（转诊）的功能。此外，还负责一些技术难点的攻关，如自动化测试，多张高清大图的流上传等。

*** 深圳市爱美购科技有限公司 - Android 开发工程师 (2014-6 至 2015-6)

负责 Android 端海淘电商 App 的开发，包括首页，商品详情，购物车，订单，微信／支付宝支付，物流查询，自定义控件等模块。其中前半年里只有自己一个人开发，从零到上线。

** 项目经历

*** 求知鸟付费课程项目 - 后台开发

主要负责[[https://studybird.wehere.me][付费课程]]的后端（业务逻辑，运营后台，推荐系统以及中间服务等）开发，同时也参与部分微信小程序和h5网站(Vue.js)的开发。在技术使用了微服务架构，在腾讯云上使用k8s容器服务部署各种语言(Spring Boot, Node.js, Go)编写的项目。

*** 活点地图 - iOS/Android App

由于iOS没有后台机制，以及用户可能根本就没有打开app去上报位置，于是在地图上查看好友的实时位置成了一个难点。通过利用iOS VoIP的特性以及服务端的配合设计了一套位置上报和获取的策略，达到了预期的目的，也降低了持续定位带来的电量消耗。可在各大市场 [[https://itunes.apple.com/cn/app/id1270657319][下载]]。

*** 么么嗖海淘 - Android App

因为电商运营经常要搞活动，首页界面变动频繁，为了保证原生体验和免去提交商店更新的耗时，实现了一个自定义模版引擎，将服务端下发的布局描述文件渲染成原生界面。使得活动界面可以随时更新而无需提交新版本，加快了运营的脚步。可在各大市场 [[http://sj.qq.com/myapp/detail.htm?apkName=com.imaygou.android][下载]]。

** 技术能力

#+BEGIN_SRC yaml
语言: 熟悉 C/Go/Java，了解 汇编/Objective-C/Swift/Kotlin/JavaScript
环境: 熟悉 Linux 环境，熟练使用 Emacs/Vim/Git/curl/tcpdump/docker 等
基础: 了解常用的数据结构和算法，了解设计模式，对 TCP/IP 和 HTTP 等网络协议有较深的理解
技术: 了解 Unix 环境下的 IO, Socket 和并发编程，熟悉 Android 开发，了解 iOS/macOS 以及前端的开发
#+END_SRC
